add index directly and remove nullable false
CodingCab/ShipTown pull request #313
Opened 2024-03-27 13:14 UTC by robgoodliffe

closes #291

2024-03-27 20:22 UTC, ArturHanusek requested changes
->nullable(false) is complete opposite to ->nullable()

            $table->string('code')->nullable(false)->default('');
===
            $table->string('code')->default('');

2024-03-27 20:22 UTC, ArturHanusek commented on database/migrations/2019_10_16_000000_core_v1.php
> +            $table->string('code')->nullable()->default('');
@robgoodliffe this is wrong, it now allows code field to be null... it shouldn't be the case

2024-03-27 20:22 UTC, ArturHanusek commented on database/migrations/2019_10_16_000000_core_v1.php
> +            $table->string('code', 5)->nullable()->unique();
@robgoodliffe same as previous comment

2024-03-27 21:19 UTC, robgoodliffe commented
@ArturHanusek should be fixed now. Apologies. Misunderstanding on my part.

2024-03-27 21:30 UTC, ArturHanusek requested changes

2024-03-27 21:30 UTC, ArturHanusek commented on database/migrations/2019_10_16_000000_core_v1.php
> +            $table->string('log_name')->index();
@robgoodliffe last one, log_name should be nullable in that case i believe

2024-03-27 21:42 UTC, robgoodliffe commented
@ArturHanusek fixed

2024-03-28 07:16 UTC, ArturHanusek approved these changes

2024-03-28 07:16 UTC, merged