#747 automatic frontend translations
CodingCab/ShipTown pull request #764
Opened 2024-12-13 16:37 UTC by rizkypujiraharja

Command `php artisan chatgpt:translate-app`

The concept is that we only need to write our text in the en.json file. Then, the program will read the list of directories in the locales folder. After that, the other language files and the en.json file will be merged.

Once the files are merged, ChatGPT will only translate the entries whose values are empty. After receiving the translations from ChatGPT, each file will be rewritten according to its language code.

2024-12-13 20:39 UTC, ArturHanusek requested changes
We need to write the test for it. 

When writing tests for feature which requires env variable to be set:
- first check if the env variable is set - mark test skipped if not ()
- perform test action

2024-12-15 09:10 UTC, rizkypujiraharja commented
https://jam.dev/c/624175e5-0da7-48e0-8fa4-33aac56b8b99

2024-12-17 00:11 UTC, rizkypujiraharja commented on app/Console/Commands/ChatgptTranslateApp.php
> +        $listFiles = $this->getFiles($dirPath);
Noted

2024-12-18 09:15 UTC, ArturHanusek commented on app/Console/Commands/ChatgptTranslateApp.php
> +        $enFileJson = file_get_contents($dirPath . '/en.json');
i think its good idea!

2024-12-20 09:46 UTC, ArturHanusek approved these changes

2024-12-20 09:47 UTC, merged